[versions]
kotlin = "1.5.21"
android-gradle = "7.0.4"
#noinspection GradleDependency causes errors
appcompat = "1.4.1"
dokka = "1.8.10"
aliuhook = "09c718c"
aliucord-gradle = "753ad25"
discord = "126021"
#noinspection GradleDependency causes errors
material = "1.5.0"
constraintlayout = "2.1.4"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
aliuhook = { module = "com.aliucord:Aliuhook", version.ref = "aliuhook" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
discord = { module = "com.discord:discord", version.ref = "discord" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
aliucord-gradle = { id = "com.aliucord.gradle", version.ref = "aliucord-gradle" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
