name: Javadoc

on:
  push:
    branches:
      - main
    paths:
      - Aliucord/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@3404b45d4c43e74e30dcad1a47fb89a0573f5a7e # v2.0.6

      - name: Generate Javadoc
        run: |
          chmod +x ./gradlew
          ./gradlew Aliucord:javadoc
          wget https://raw.githubusercontent.com/Aliucord/Javadoc/fd2c6e4fdc3d3f4a2934bc19f2ce1d8e34cfa251/README.md -O Aliucord/build/docs/javadoc/README.md

      - name: Push Javadoc
        uses: cpina/github-action-push-to-another-repository@2ebe0cc15fc6a8e63c3658c119525bf1aead4418
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_PAT_GITHUB }}
        with:
          source-directory: Aliucord/build/docs/javadoc
          destination-github-username: Aliucord
          destination-repository-name: Javadoc
          user-email: actions@github.com
          user-name: GitHub Actions
          commit-message: Generate Javadoc for ORIGIN_COMMIT
          target-branch: main
